### ISSUE TITLE
Docker readme states two times RADIUS_DB_NAME

### ISSUE THREAD

**Issue by gintsgints** [tpdock/freeradius#4]
instead:
```
 -e RADIUS_DB_NAME=mysql \
  -e RADIUS_DB_NAME=freeradius \
```

probably is meant to be:
```
 -e RADIUS_DB_HOST=mysql \
  -e RADIUS_DB_NAME=freeradius \
```

**Comment by gintsgints** [comment]
Also would be nice to attach docker-compose example like:
```
radius:
  image: tpdock/freeradius
  restart: always
  links:
  - "mysql:db"
  ports:
  - "1812:1812/udp"
  - "1813:1813/udp"
  environment:
  - RADIUS_LISTEN_IP=*
  - RADIUS_CLIENTS=secret@127.0.0.1
  - RADIUS_SQL=true
  - RADIUS_DB_HOST=db
  - RADIUS_DB_NAME=radius
  - RADIUS_DB_USERNAME=radius
  - RADIUS_DB_PASSWORD=radius_234
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "20"

mysql:
  image: mysql:5.7.22
  restart: always
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=root_234
  - MYSQL_DATABASE=radius
  - MYSQL_USER=radius
  - MYSQL_PASSWORD=radius_234
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "20"
```
